### ISSUE TITLE
Use tidyselect semantics instead of `vars()`

### ISSUE THREAD

**Issue by gorcha** [socialresearchcentre/testdat#36]
Questioning this one because it will potentially break everything...

Currently we use `vars()` to specify variable sets everywhere. We should move to the new [tidyselect semantics](https://tidyselect.r-lib.org/articles/tidyselect.html), which are similar but don't use `quos()` in the same way.

Needs a bit more investigation to see how feasible it is.

**Comment by kinto-b** [comment]
Yeah, for sure. I'll install the dev version and use it for a week or so to see if anything breaks unexpectedly. Just gimme a shout when the dev branch is usable

**Comment by gorcha** [comment]
To clarify, I'm 100% certain it'll break things 😛 Just not sure how badly/how much work it'll be to update. I think it'll mostly just be switching out `vars()` for `c()`

**Comment by kinto-b** [comment]
Ah, sorry I misread the above and got the impression `vars()` was compatible with both approaches. That's unfortunate. I suppose it would be possible to force the compatibility:

```r
my_selector <- function(.data, cols) {
    xpr <- enquo(cols)
    uses_vars <- identical(as.list(quo_get_expr(xpr))[[1]], quote(vars))
    if (uses_vars) {
        dplyr::select_at(.data, cols)
    } else {
        dplyr::select(.data, !!xpr)
    }
}
```

But it's a bit risky

**Comment by gorcha** [comment]
Yeah I think it's better to just do a hard switch, it'll be a nightmare to maintain support for both `vars()` and the tidyselect semantics.
From the user side it should be relatively straightforward to deal with the update (replace `vars()` with `c()`), at least in theory.
