### ISSUE TITLE
Create testdat hex logo

### ISSUE THREAD

**Issue by gorcha** [socialresearchcentre/testdat#42]
The most essential part!

But what? See testthat logo for inspiration:
![testthat logo](https://raw.githubusercontent.com/r-lib/testthat/master/man/figures/logo.png)

**Comment by kinto-b** [comment]
Not sure about the colours, but what do you think about this for a concept

![testdat-logo-icon](https://user-images.githubusercontent.com/61998181/134290889-9551d9e1-486e-4d34-9341-9bbf44056d31.png)

**Comment by gorcha** [comment]
Where'd the hex you posted go @kinto-b?

**Comment by kinto-b** [comment]
Yo! Sorry for the delay. I came back to it a little while after I'd posted it and thought better of it. As an alternative, I just whipped this up in 30s:

![testdat-logo(1)](https://user-images.githubusercontent.com/61998181/135800129-9db90e4a-92ea-47b6-91e4-dcc5ae05023c.png)

**Comment by gorcha** [comment]
Haha I kind of liked it :stuck_out_tongue: 
This is cool too! Happy with this if you are, not too fussed really. Maybe make the "dat" more bold than the "test" for emphasis?

**Comment by kinto-b** [comment]
You can't actually do bolding in excalidraw, haha, but how's this ^

**Comment by gorcha** [comment]
I like it!
