### ISSUE TITLE
What should the `set_testdata()` return value be?

### ISSUE THREAD

**Issue by gorcha** [socialresearchcentre/testdat#44]
Currently it returns the old test data set. This is good for things like the `with_testdata()` function, but I feel like it's more normal to return the input data. This would also make it work more nicely in pipes.

What do you think @kinto-b?

**Comment by kinto-b** [comment]
Returning the old data feels like a more conventional choice to me, and I don't think the alternative would be that useful (not useful enough to upset convention anyway). So I think we should keep it how it is

**Comment by gorcha** [comment]
OK cool, thanks!
