### ISSUE TITLE
Update `chk_blank()`

### ISSUE THREAD

**Issue by gorcha** [socialresearchcentre/testdat#46]
Basically the same as the srcutils change for `is_blank()` (socialresearchcentre/srcutils#95) - using `%in%` is unnecessarily slow.
```r
chk_blank <- function(x) {
  if (is.character(x)) {
    is.na(x) | x == ""
  } else {
    is.na(x)
  }
}
```

I noticed the final `is_blank()` had a couple of extra bits there, would be good to get your feedback on these @kinto-b:
* There is a `stopifnot` in the character block to check for residual `NA` values - I think we have a guarantee of no `NA` values already because of the way we're checking, so going to leave this out.
* `is_blank()` checks for `""` in factors as well as character variables. I'm not sure how I feel about this for factors since they're conceptually quite different (i.e. I think it's reasonable to assume the user has appropriately checked their values), although this would be a breaking change.

**Comment by kinto-b** [comment]
Yeah, I don't think the `stopifnot()` clause is necessary. I'm not sure about factors though. I might put it to the team in an oblique way to see what they find most intuitive. I'll ask them to fill in the blanks and get back to you:

```r
x <- c("cat", "dog", "", "cat", NA)
chk_blank(x)
#> FALSE FALSE TRUE FALSE TRUE

y <- factor(x)
chk_blank(y)
#> FALSE FALSE LGL1 FALSE LGL2
```

**Comment by gorcha** [comment]
I'm kind of torn - if factors are treated like character then a `""` level on a factor will be treated as a blank. On the one hand this makes sense since the value is `""`, but on the other it's an assigned level :shrug: 

I'm going to treat factors like characters for the moment since that's the current behaviour, but might change my mind at some point :stuck_out_tongue:

**Comment by kinto-b** [comment]
Yeah, there weren't any strong intuitions in the team
