### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kinto-b** [socialresearchcentre/testdat#52]
Looks good to me. Only thing that should be fixed before this is merged are the links in the vignette. 

Actually the whole "Categories" section probably needs a revamp given that it doesn't really align with the "Expectations" section of the "Reference" page.

But looking at the "Reference" page now, it's still not organized in the best possible way. 

For instance, do the "Expectations - auto-generated" really constitute a reasonable category? I now realise it made more sense before as "value expectations", but that's still not perfect. Perhaps "Expectations - format" for pattern, length, date, and so on, "Expectations - values" for value and range, and something else for text missingness (which are potentially questionable given the existence of expect_base). 

Additionally, the descriptions are inconsistent. Some have "checks" in the description, others don't, etc.

_Originally posted by @kinto-b in https://github.com/socialresearchcentre/testdat/pull/45#pullrequestreview-754669970_

**Comment by gorcha** [comment]
Ta! Also see #34

**Comment by gorcha** [comment]
Awesome, that documentation structure looks great!

The only other thought I had is combining the corresponding expect and chk functions into the one man page, but that might be a bit weird because the function signature and use case are quite different, what do you think?

Personally I prefer `@rdname` to `@describeIn` but I can't actually remember why so not super fussed. Does `@describeIn` still include separate usage entries?

**Comment by kinto-b** [comment]
@gorcha Sweet :) 

Yeah, it seems to do exactly rdname does only with the addition of that Functions section:

![image](https://user-images.githubusercontent.com/61998181/138019399-7fba06a9-1779-42ff-9199-790b4ccabe7c.png)

I think it's better to keep them separate and link them using `@seealso` and/or by mentioning the `chk_*()` function in the corresponding `expect_*()` man page.

**Comment by kinto-b** [comment]
@gorcha slightly off topic, but I'm just documenting the chk_text_miss functions --- what exactly is the envisioned use-case for these?

**Comment by gorcha** [comment]
Good question! They're related to some of the text cleaning in the sample cleaning functions, essentially for making sure that any missing placeholders that might have crept in from other systems are removed.

Not 100% sure of their usefulness, it's almost a special case of `chk_values()` or `!chk_values()`.

**Comment by gorcha** [comment]
Also yes definitely re: `chk_pattern()` - I think it should be renamed to `chk_regex()` since that seems clearer and more direct to me.
