### ISSUE TITLE
Rename `chk_pattern()`

### ISSUE THREAD

**Issue by kinto-b** [socialresearchcentre/testdat#53]
Also yes definitely re: `chk_pattern()` - I think it should be renamed to `chk_regex()` since that seems clearer and more direct to me.

_Originally posted by @gorcha in https://github.com/socialresearchcentre/testdat/issues/52#issuecomment-947289585_

**Comment by gorcha** [comment]
Actually I'm reconsidering this, since technically `str_detect()` can take non-regex patterns.
Maybe both, or is that too much/unnecessary?

**Comment by kinto-b** [comment]
Hm, both is unappealing. I suppose it's a bit more of a hassle to rename `expect_regex()` since that's much more actively in use

**Comment by gorcha** [comment]
Yeah true. I guess regex captures the intention better as well. Probably just over thinking things!
