### ISSUE TITLE
`output_results_excel ` writes a corrupted excel file

### ISSUE THREAD

**Issue by g-hyo** [socialresearchcentre/testdat#56]
Just ran into this with GOS. 

```
x <- test_dir(full_path, stop_on_failure = FALSE, stop_on_warning = FALSE)

res_path <- paste0(full_path, "/results_pop_final_clean.xlsx")
output_results_excel(x, res_path)
```

One of the base checks had a reference to `E386` which is no longer in the data. This resulted in the base check spitting out an error:
```
`Problem with `mutate()` input `..1`. [31mx[39m object 'E386' not found [34mi[39m Input `..1` is `!E386 %in% c(NA, "", 9)`.`
```

`test_dir` didn't actually stop due to this error, and the output produced is a corrupted excel file with a blank sheet like so
![image](https://user-images.githubusercontent.com/14864611/138179901-2b996774-ee39-4d36-baa1-c55e64fb913f.png)

Obviously there _should_ be no errors in the first place when running unit tests, but it could be useful to still be able to access the output somehow to quickly diagnose the issue. In a CSV, the error is output.
![image](https://user-images.githubusercontent.com/14864611/138180150-fa795684-97c6-40ed-80e9-001924235f55.png)

We could also just have it such that `output_results_excel` spits an error and doesn't run if there are any errors in the tests (probably the simplest solution)

**Comment by kinto-b** [comment]
Looks like a character encoding issue. The tidyverse uses UTF-8 characters and applies colouring to their error messages. It would appear that this doesn't play nicely with whatever encoding `openxlsx` uses. 

We can resolve simply by removing non-printable ascii characters from the description. @gorcha How does that sound to you?
