### ISSUE TITLE
pkgdown is unreachable

### ISSUE THREAD

**Issue by kinto-b** [socialresearchcentre/testdat#58]
Looks like the pkgdown code has been placed within a `dev` directory under the root level

**Comment by gorcha** [comment]
This is because of the "development mode" setting - it deploys to /dev when there's a .900* version component, and since there hasn't been a release yet it's only deployed there.
https://github.com/socialresearchcentre/testdat/blob/055aacf47d8fc0edc818b64bab377b12536aecf4/_pkgdown.yml#L5-L6

**Comment by gorcha** [comment]
It'll deploy properly once the version is bumped.

**Comment by kinto-b** [comment]
Ah yup, easy
